### ISSUE TITLE
Dragon Armor causes disconnect from server

### ISSUE THREAD

**Issue by ZenoMetal** [kwpugh/gobber_fabric#1]
Hi, whenever I join my Server and I equip the Dragon Armor, no matter what piece, I get kicked

```
[18:17:38] [Server thread/INFO]: Sending config to ZenoMetal (1924f773-af7f-4925-8a05-fe45bd81a01b)
[18:17:38] [Server thread/INFO]: [STDOUT]: sending loot to ZenoMetal
[18:17:51] [Server thread/WARN]: ZenoMetal moved too quickly! -72.19590977921322,-77.0,-57.92636563461883
[18:19:13] [Server thread/WARN]: Failed to handle packet for /88.130.154.52:16002
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:498) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-1.16.5.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1656.method_7248(F)V
	at com.kwpugh.gobber2.items.armor.DragonArmor.tickArmor(DragonArmor.java:66) ~[Gobber2-Fabric_1.16.5-2.3.66.jar:?]
	at net.minecraft.class_1657.handler$bin000$gobberTickArmor(class_1657.java:11318) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-1.16.5.jar:?]
	... 9 more
[18:19:13] [Server thread/INFO]: ZenoMetal lost connection: Internal server error
[18:19:13] [Server thread/INFO]: ZenoMetal left the game
```

**Comment by kwpugh** [comment]
Fixed in v67

**Comment by ZenoMetal** [comment]
Nice :)
