### ISSUE TITLE
[1.16.5] Client-side crash with Sodium

### ISSUE THREAD

**Issue by enosich** [kwpugh/gobber_fabric#23]
NullPointerException when entering new dimension with Sodium installed. Does not crash the server.

**Comment by kwpugh** [comment]
Crash report?

There seem to be several mods that crash with Sodium.

**Comment by enosich** [comment]
I'll give you a brief crash report, i just have some notes here. The full log is on my desktop and i'm not at it right now. null pointer exception is thrown when getPortalBase from the customportalapi and sodium's SmoothBiomeColorBlender's getBlockColor methods interact.

**Comment by enosich** [comment]
`[22:47:16] [main/INFO]: [STDOUT]: Minimap updated server level id: -1590473618 for world ResourceKey[minecraft:dimension / gobber2:mining]
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: java.lang.NullPointerException
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.kyrptonaught.customportalapi.CustomPortalBlock.getPortalBase(CustomPortalBlock.java:120)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.kyrptonaught.customportalapi.CustomPortalBlock.getPortalBase(CustomPortalBlock.java:121)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.kyrptonaught.customportalapi.client.CustomPortalsModClient.lambda$onInitializeClient$0(CustomPortalsModClient.java:29)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getBlockColor(SmoothBiomeColorBlender.java:49)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getInterpolatedVertexColor(SmoothBiomeColorBlender.java:69)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getColors(SmoothBiomeColorBlender.java:30)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuad(BlockRenderer.java:123)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:108)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:81)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:43)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:91)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:347)
[22:47:17] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by kwpugh** [comment]
Yeah, I think this was an issue that the author of CustomPortalsAPI resolved in a later version.  I think it has to do with the mod loading order and when the API gets called.

I will take a look.

**Comment by kwpugh** [comment]
Hmm, looks like it got fixed in beta 14 of the api and I'm using beta 16.

https://github.com/kyrptonaught/customportalapi/issues/2

**Comment by enosich** [comment]
so it seems as though the issue's back, eh?

**Comment by kwpugh** [comment]
maybe.  I posted this issue into the authors previous issue.

We will see.

**Comment by enosich** [comment]
Let me know if there's anything I can do to help. I might comb through beta 6 and see if there's something obvious staring us in the face.

**Comment by kwpugh** [comment]
[Gobber2-Fabric_1.16.5-2.3.72.jar.zip](https://github.com/kwpugh/gobber_fabric/files/6737061/Gobber2-Fabric_1.16.5-2.3.72.jar.zip)

Give this version a try

**Comment by enosich** [comment]
I'll see if it crashes my game. I'm not pushing it into my server because... obviously.

**Comment by kwpugh** [comment]
Understood, if that doesn't fix, not sure what will.  The API had me update to beta 32 of the portals API.

**Comment by kwpugh** [comment]
I had to rip put Curios support to be able to update, because the Curios supporting mavens went bye bye.

**Comment by enosich** [comment]
That did the trick. That's honestly brutal, hopefully there'll be a fix for the curios. The beta 32 was the thing that fixed it?

**Comment by kwpugh** [comment]
Great.  Frankly, I have moved on to 1.17, so I won't be doing any more work in 1.16.5

Enjoy.

**Comment by enosich** [comment]
Yeah i totally understand. Thank you so much for doing work on this outdated version. Can you please push the fix to this repository so I can fork it as an LTS version?

**Comment by kwpugh** [comment]
I'll see what I can do, I have been having GitHub issue since the upgrade to 1.17, Java 16, and the new Gradle.

**Comment by enosich** [comment]
Understandable - thank you so much for this.

**Comment by kwpugh** [comment]
I can't push to existing, here is a new version for 1.16.5.

https://github.com/kwpugh/gobber_fabric-1.16.5
